/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef TAPJOY_AUTODEFS_H
#define TAPJOY_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_TAPJOY_NAME "Tapjoy"
#define S3E_EXT_TAPJOY_HASH 0x1d8ff2bc

#endif /* !TAPJOY_AUTODEFS_H */
